### ISSUE TITLE
USDC rewards are not withdrawable from QS front end

### ISSUE THREAD

**Issue by joe-bowman** [quicksilver-zone/quicksilver#1635]
## Summary of Bug

A number of users have reported USDC earned from Dydx is not withdrawable from the QS front end.

@chalabi2 states that the denom is not listed on the Skip API

I believe we need to add all rewards denoms to chain registry for them to show on the Skip API.
Secondly,  in order for the same to show on mintscan, we need to ensure they are listed in the Mintscan repo.

## Task

Go through supply, and determine which IBC denoms are received as rewards from host zones. Add these denoms to chain registry and mintscan under the quicksilver-2 zone.

**Comment by joe-bowman** [comment]
Added USDC here: https://github.com/cosmos/chain-registry/pull/4744

If this works, will add other following assets:

```
ibc/13B2C536BB057AC79D5616B8EA1B9540EC1F2170718CAFF6F0083C966FFFED0B
denom_trace:
  base_denom: uosmo
  path: transfer/channel-2

ibc/23873BF9F23294964962F1405BE0A8EB3C0DEEFC4D6BDB20915A1B62E3041D9E
denom_trace:
  base_denom: stuumee
  path: transfer/channel-1/transfer/channel-391

ibc/24612FC801FA8931656D8BA382BDBC6B237040A5B0CB50A69CC7C82855D6EEAA
denom_trace:
  base_denom: stucmdx
  path: transfer/channel-1/transfer/channel-391

ibc/25A01BCED23530945E74C17A63C29DAD5970F7405B398681D015738B51A0B64C
denom_trace:
  base_denom: ppica
  path: transfer/channel-94

ibc/2B00B177283C6B860DBF28D087BEF6C93BF8AC4CD69050518E83C4EF2F4830FB
denom_trace:
  base_denom: staevmos
  path: transfer/channel-1/transfer/channel-391

ibc/3C2F8B194737E68ABBAD18CB83BD80ABF22E11AF2DC9C976A88F106F05F41D8F
denom_trace:
  base_denom: uluna
  path: transfer/channel-82

ibc/3EDFD287DA7552429E1148BF954AB6F44F7C9730567964208B3052E6DDF18D08
denom_trace:
  base_denom: ujuno
  path: transfer/channel-86

ibc/49BAE4CD2172833F14000627DA87ED8024AD46A38D6ED33F6239F22B5832F958
denom_trace:
  base_denom: ustars
  path: transfer/channel-0

ibc/4B3F2630F1EC02190C3A765114709934F8CCE8F577129DC898CF1627D02CE0D1
denom_trace:
  base_denom: ubld
  path: transfer/channel-125

ibc/53A36743DDB5C5B8DFBC5C7D3360B18C47111BB9EADED099465DCF123086E625
denom_trace:
  base_denom: untrn
  path: transfer/channel-1/transfer/channel-569

ibc/56446D416C5998249DD4F0E52C9C973AD9F4D5D9D25FF99C6D37240712C7A1ED
denom_trace:
  base_denom: aarch
  path: transfer/channel-116

ibc/5666A86DCC869C75F69A7938AD6DCFECAC4A09C73522599E7A85B10143E5FBD2
denom_trace:
  base_denom: uusdc
  path: transfer/channel-164/transfer/channel-0

ibc/5B5C6253F505A05809C899CDB26FAD6464657889F15D5699DC6F6B6AFFE9FDA4
denom_trace:
  base_denom: ustars
  path: transfer/channel-2/transfer/channel-75

ibc/5CC131485B2E91C2A1BE0AD5D62086D7BA14552F1C81D1FB05B32DCE1A535D13
denom_trace:
  base_denom: adydx
  path: transfer/channel-164

ibc/5F78C42BCC76287AE6B3185C6C1455DFFF8D805B1847F94B9B625384B93885C7
denom_trace:
  base_denom: uatom
  path: transfer/channel-2/transfer/channel-0

ibc/73E97EB411B29C6F989C35D277D1A7FC65083572F102AC6BD101884EE9FB2C9F
denom_trace:
  base_denom: aevmos
  path: transfer/channel-7

ibc/79322BC2C577D073BA8830A8CBF813A8417C640B4702C724D7CA2197EDE22D9C
denom_trace:
  base_denom: stuluna
  path: transfer/channel-1/transfer/channel-391

ibc/8E5300A7730B25828BADAF67C782C6673D5C0B68C72A78B0AA06705CA746879C
denom_trace:
  base_denom: stuatom
  path: transfer/channel-1/transfer/channel-391


ibc/9F82EA00FB6FEDFD91E9F832BA955EF381E88D80C40DF3B5192B57E5DB139F49
denom_trace:
  base_denom: stusomm
  path: transfer/channel-1/transfer/channel-391

ibc/A7E38774F447445DB94A8ED00BEE78EFC43EED7A732D314D3F7F4AB743993E9F
denom_trace:
  base_denom: uregen
  path: transfer/channel-17

ibc/BFF8BC09B94E2EA90B64961A181D2383280FFA7847109DE1AB4ECA366466462A
denom_trace:
  base_denom: usomm
  path: transfer/channel-101

ibc/C4CFF46FD6DE35CA4CF4CE031E643C8FDC9BA4B99AE598E9B0ED98FE3A2319F9
denom_trace:
  base_denom: uatom
  path: transfer/channel-1

ibc/CACFB6FEEC434B66254E2E27B2ABAD991171212EC8F67C566024D90490B7A079
denom_trace:
  base_denom: ustrd
  path: transfer/channel-1/transfer/channel-391

ibc/D474553C1A29257F4EC4056C346FCF7EF6F979909E9ACF88BA259C1ED2C54036
denom_trace:
  base_denom: uumee
  path: transfer/channel-49

ibc/DE8815710B5A23FEBF188F0EE0DBA96FD4CBE154D506D42EAD885CB805C64055
denom_trace:
  base_denom: stustars
  path: transfer/channel-1/transfer/channel-391

ibc/E7395B1DECD14A8B7F9AA60083119E395DA8E37A1DCAA8B9ED07ED8D4F7E48E3
denom_trace:
  base_denom: usaga
  path: transfer/channel-170

ibc/E9BBE9BBF0925155892D6E47553E83B8476C880F65DEB33859E751C0B107B0B1
denom_trace:
  base_denom: stinj
  path: transfer/channel-1/transfer/channel-391

ibc/EF392FCB1D863D7DC58034FE2806000F543DDFC9FC9B8B92969B5AE4906CD57E
denom_trace:
  base_denom: stujuno
  path: transfer/channel-1/transfer/channel-391

ibc/FD89ED1C06FAEE7CA9F94BA0C3E813ADE4489DD8259435F447BC031D5C4A6DE3
denom_trace:
  base_denom: stuosmo
  path: transfer/channel-1/transfer/channel-391
```
